
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Where to find user code.
USER_DIR = ./

# Flags passed to the preprocessor.
CPPFLAGS += -I./external/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -Wno-c++11-extensions

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = unittest

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = ./external/include/gtest/*.h \
                ./external/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS) temp

clean :
	rm -f $(TESTS) *.o *.pyc .ycm_extra_conf.pyc temp

main.o : $(USER_DIR)/main.cc $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/main.cc
temp : main.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

test.o : $(USER_DIR/test.cc $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/test.cc
unittest : ./external/lib/gtest_main.a test.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ && ./unittest
